
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'NUMBER PRINT STRINGstatement : PRINT expressionexpression : STRINGexpression : NUMBER'
    
_lr_action_items = {'PRINT':([0,],[2,]),'$end':([1,3,4,5,],[0,-1,-2,-3,]),'STRING':([2,],[4,]),'NUMBER':([2,],[5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'statement':([0,],[1,]),'expression':([2,],[3,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> statement","S'",1,None,None,None),
  ('statement -> PRINT expression','statement',2,'p_statement_print','printstatment.py',29),
  ('expression -> STRING','expression',1,'p_expression_string','printstatment.py',33),
  ('expression -> NUMBER','expression',1,'p_expression_number','printstatment.py',37),
]
